/* For Morph */
/* UDP payload BNF syntax */
/* Simulation at bnfplayground.pauliankline.com */
/* Bilal Boudjemline (lalBi94 on GitHub) */

<payload> 
    ::= <cl_action> | <heart_beat>

/* payload pattern */
<cl_action> ::= "CL_ACTION" "|" <eternal_id> ("|" (<PHYSICAL_EVENTS> | <NON_PHYSICAL_PROCESS>))+
<heart_beat> ::= "HEART_BEAT" "|" <eternal_id>

/* litteral tokens */
<eternal_id> 
    ::= <ALPHA_NUMERICAL_EID> <ALPHA_NUMERICAL_EID> <ALPHA_NUMERICAL_EID> <ALPHA_NUMERICAL_EID>
    <ALPHA_NUMERICAL_EID> <ALPHA_NUMERICAL_EID> <ALPHA_NUMERICAL_EID> <ALPHA_NUMERICAL_EID>

<ALPHA_NUMERICAL_EID>
    ::= [A-Z] | [0-9] | [a-z]

<FLOAT>
    ::= ("-")? [1-9]+ [0-9]* "." [0-9]+

<PHYSICAL_EVENTS>
    ::= "MoveForward"
	| "MoveBackward"
	| "MoveLeft"
	| "MoveRight"
	| "Jump"
	| "Falling"
	| "Glide"
	| "Sprint"

<NON_PHYSICAL_PROCESS>
    ::= "Sneak"
    | "Dance"