/* For Morph */
/* UDP payload BNF syntax */
/* Simulation at bnfplayground.pauliankline.com */
/* Bilal Boudjemline (lalBi94 on GitHub) */

<payload> 
    ::= <checkup> 
    | <hello>
    | <broadcast_neighbors>

/* payload pattern */
<checkup> 
    ::= "CHECKUP" 
    "|" <eternal_id> "|" <FLOAT> 
    "|" <FLOAT> "|" <FLOAT> "|" <FLOAT>
    "|" <FLOAT> "|" <FLOAT> "|" <FLOAT>

<hello>
    ::= "HELLO"
    "|" <eternal_id>

<broadcast_neighbors>
    ::= "BRD_NEIGH"
    "|" <eternal_id> "|" <FLOAT> 
    "|" <FLOAT> "|" <FLOAT> "|" <FLOAT>
    "|" <FLOAT> "|" <FLOAT> "|" <FLOAT>

/* litteral tokens */
<eternal_id> 
    ::= <ALPHA_NUMERICAL_EID> <ALPHA_NUMERICAL_EID> <ALPHA_NUMERICAL_EID> <ALPHA_NUMERICAL_EID>
    <ALPHA_NUMERICAL_EID> <ALPHA_NUMERICAL_EID> <ALPHA_NUMERICAL_EID> <ALPHA_NUMERICAL_EID>

<ALPHA_NUMERICAL_EID>
    ::= [A-Z] | [0-9] | [a-z]

<FLOAT>
    ::= ("-")? [1-9]+ [0-9]* "." [0-9]+